# Generated by Django 4.2 on 2023-04-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, default='kPNZhbRh8DzX', max_length=12, null=True, unique=True),
        ),
    ]
