# Generated by Django 4.2 on 2023-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, default='JiEX7IfWCgWi', max_length=12, null=True, unique=True),
        ),
    ]
